---
- name: Remove system packages
  apt:
    name: "{{ item }}"
    state: absent
    force: true
    force_apt_get: true
  with_items:
    - "{{ packages_to_remove }}"
  tags: ["remove", "packages"]
