---
- name: Ensure required system packages are installed
  apt:
    name: "{{ item }}"
    state: present
    force: true
    force_apt_get: true
  with_items:
    - "{{ packages_to_add }}"
  tags: ["add", "packages", "install"]
