---
- name: Set role facts
  set_fact:
    settings: "{{ role_debian_system_packages_helper.settings }}"
    packages_to_add: "{{ role_debian_system_packages_helper.packages.add }}"
    packages_to_remove: "{{ role_debian_system_packages_helper.packages.remove }}"
  tags: ["install", "configure"]
